export interface StaticReview {
  name: string;
  flag: string;
  country: string;
  rating: number;
  trip: string;
  date: string;
  platform: string;
  avatar: string;
  tripPhoto: string;
  photoPosition?: string;
  text: string;
}

export const staticReviews: StaticReview[] = [
  {
    name: 'Himanshu',
    flag: '🇮🇳',
    country: 'Ambala, Haryana',
    rating: 5,
    trip: 'Manali & Rohtang Pass',
    date: 'July 2026',
    platform: 'Google',
    avatar: '/reviews/himanshu-manali.jpg',
    tripPhoto: '/reviews/himanshu-manali.jpg',
    photoPosition: 'center 68%',
    text: 'Our Manali and Rohtang Pass trip with YLOO Trips was simply unforgettable. The snow-covered mountains, breathtaking views, and exciting activities at Rohtang Pass made the journey truly special. The hotels were comfortable, the transportation was smooth, and everything was perfectly organized. Thank you, YLOO Trips, for an amazing holiday. Highly recommended!',
  },
  {
    name: 'Jatin',
    flag: '🇮🇳',
    country: 'Alwar, Rajasthan',
    rating: 5,
    trip: 'Vietnam Group Trip',
    date: 'July 2026',
    platform: 'Google',
    avatar: '/reviews/jatin-vietnam.jpg',
    tripPhoto: '/reviews/jatin-vietnam.jpg',
    photoPosition: 'center 33%',
    text: 'I compared my holiday package with Booking.com and MakeMyTrips and was pleasantly surprised that YLOO Trips provided a more budget-friendly package with excellent hotels and services. The entire trip was perfectly planned, and everything exceeded my expectations. Highly recommended!',
  },
  {
    name: 'Sagar',
    flag: '🇮🇳',
    country: 'Gurugram, Haryana',
    rating: 5,
    trip: 'Kashmir Tour Package',
    date: 'May 2026',
    platform: 'Google',
    avatar: '/reviews/sagar-kashmir.jpg',
    tripPhoto: '/reviews/sagar-kashmir.jpg',
    photoPosition: 'center 45%',
    text: 'Our Kashmir trip with YLOO Trips was absolutely wonderful. From the beautiful valleys of Gulmarg and Pahalgam to the peaceful Dal Lake in Srinagar, every moment was memorable. The hotels, transportation, and sightseeing were perfectly arranged. The entire journey was smooth and stress-free. Thank you, YLOO Trips, for giving us an unforgettable holiday. Highly recommended!',
  },
  {
    name: 'Prerna and Aditya',
    flag: '🇮🇳',
    country: 'Rohtak, Haryana',
    rating: 5,
    trip: 'Darjeeling Package',
    date: 'July 2026',
    platform: 'Google',
    avatar: '/reviews/aditya-prerna-darjeeling.jpg',
    tripPhoto: '/reviews/aditya-prerna-darjeeling.jpg',
    photoPosition: 'center 22%',
    text: 'I recently visited Darjeeling, and it was an amazing experience. The weather was pleasant, the scenery was beautiful, and the mountains were absolutely breathtaking. Every part of the trip was well planned and hassle-free. It was truly one of the best trips I have ever had. Thank you, YLOO Trips, for making this journey so memorable. Highly recommended!',
  },
  {
    name: 'Avnish and Shivani',
    flag: '🇮🇳',
    country: 'Gurugram, Haryana',
    rating: 5,
    trip: 'Lakshadweep Island Package',
    date: 'April 2026',
    platform: 'Google',
    avatar: '/reviews/lakshadweep-couple.jpg',
    tripPhoto: '/reviews/lakshadweep-couple.jpg',
    photoPosition: 'center 43%',
    text: 'Recently visited Lakshadweep through Ylootrips.com and it was an incredible experience! The itinerary was well-planned, accommodations were comfortable, and the entire trip was smooth from start to finish. The team was supportive and always available for assistance. Lakshadweep itself is breathtaking, and Ylootrips made the journey even more memorable. Highly recommend booking with them!',
  },
  {
    name: 'Neha & Rohan Sharma',
    flag: '🇮🇳',
    country: 'Mumbai, Maharashtra',
    rating: 5,
    trip: 'Bali Honeymoon Package',
    date: 'March 2026',
    platform: 'Google',
    avatar: '/reviews/neha-rohan-bali.jpg',
    tripPhoto: '/reviews/neha-rohan-bali.jpg',
    photoPosition: 'center 22%',
    text: 'Humari Bali honeymoon bilkul sapne jaisi thi! Overwater villa, private dinner, volcano sunrise — YlooTrips ne har cheez arrange ki. Paise kamaal ka vasool hua. Dil se shukriya team ko! 🙏',
  },
  {
    name: 'Aditya Nair',
    flag: '🇮🇳',
    country: 'Bangalore, Karnataka',
    rating: 5,
    trip: 'Thailand Budget Trip',
    date: 'February 2026',
    platform: 'Google',
    avatar: '/reviews/aditya-nair-thailand.jpg',
    tripPhoto: '/reviews/aditya-nair-thailand.jpg',
    photoPosition: 'center 28%',
    text: 'Pehli international trip thi — Thailand ne expectations se kaafi zyada diya. Phi Phi Islands toh zindagi bhar yaad rahegi. Coordinator WhatsApp pe hamesha available tha. Har rupee worth it!',
  },
  {
    name: 'Vikram & Ananya Singh',
    flag: '🇮🇳',
    country: 'New Delhi, India',
    rating: 5,
    trip: 'Dubai Tour Package',
    date: 'January 2026',
    platform: 'TripAdvisor',
    avatar: '/reviews/vikram-ananya-dubai.jpg',
    tripPhoto: '/reviews/vikram-ananya-dubai.jpg',
    photoPosition: 'center 22%',
    text: 'Desert safari, Burj Khalifa, Dubai Mall — sab kuch perfect tha. Visa ka koi tension nahi, YlooTrips ne sab handle kiya. Ek baar aur zaroor jayenge. Highly recommend karta hoon sabko! 👍',
  },
  {
    name: 'Meera & Suresh Iyer',
    flag: '🇮🇳',
    country: 'Chennai, Tamil Nadu',
    rating: 5,
    trip: 'Kerala Backwaters Tour',
    date: 'December 2025',
    platform: 'Google',
    avatar: '/reviews/meera-suresh-kerala.jpg',
    tripPhoto: '/reviews/meera-suresh-kerala.jpg',
    photoPosition: 'center 28%',
    text: 'Anniversary trip ke liye Kerala choose kiya — YlooTrips ki team ne jo itinerary banaya woh outstanding tha. Houseboat pe sunset dekhna aur fresh Kerala food… aisi memories jo kabhi nahi bhoolenge.',
  },
  {
    name: 'Rajan & Preethi Pillai',
    flag: '🇮🇳',
    country: 'Kochi, Kerala',
    rating: 5,
    trip: 'Maldives Luxury Package',
    date: 'February 2026',
    platform: 'Google',
    avatar: '/reviews/rajan-preethi-maldives.jpg',
    tripPhoto: '/reviews/rajan-preethi-maldives.jpg',
    photoPosition: 'center 22%',
    text: 'Maldives mein overwater villa — yeh sirf sapne mein hota tha, lekin YlooTrips ne sach kar dikhaya. Dolphin cruise aur sandbank picnic best experiences rahe. Poori team ka bahut shukriya! ❤️',
  },
  {
    name: 'Karan Malhotra',
    flag: '🇮🇳',
    country: 'Chandigarh, Punjab',
    rating: 5,
    trip: '7-Day Rajasthan Heritage',
    date: 'November 2025',
    platform: 'Google',
    avatar: '/reviews/karan-rajasthan.jpg',
    tripPhoto: '/reviews/karan-rajasthan.jpg',
    photoPosition: 'center 28%',
    text: 'Rajasthan trip ekdum mast rahi yaar! Jaipur, Jodhpur, Udaipur — teen cities, teen alag worlds. Private car aur guide tha, koi rush nahi. Jitni photos li sab Instagram pe viral ho gayi 😄',
  },
  {
    name: 'Sarah Mitchell',
    flag: '🇺🇸',
    country: 'San Francisco, USA',
    rating: 5,
    trip: '10-Day Golden Triangle',
    date: 'March 2026',
    platform: 'Google',
    avatar: '/reviews/sarah-mitchell-india.jpg',
    tripPhoto: '/reviews/sarah-mitchell-india.jpg',
    photoPosition: 'center 42%',
    text: 'The Taj Mahal at sunrise was indescribable — I still get chills. YlooTrips made our first India trip absolutely seamless. Our guide knew stories about every monument. India is intense in the best way.',
  },
  {
    name: 'James & Emma Hargreaves',
    flag: '🇬🇧',
    country: 'London, UK',
    rating: 5,
    trip: '14-Day Kerala & South India',
    date: 'February 2026',
    platform: 'TripAdvisor',
    avatar: '/reviews/james-emma-kerala.jpg',
    tripPhoto: '/reviews/james-emma-kerala.jpg',
    photoPosition: 'center 55%',
    text: 'The Kerala houseboat was the most romantic two days of our lives. YlooTrips answered every WhatsApp within minutes — even for last-minute hotel changes. Five stars without hesitation.',
  },
  {
    name: 'Lachlan Burgess',
    flag: '🇦🇺',
    country: 'Melbourne, Australia',
    rating: 5,
    trip: '7-Day Rajasthan Heritage',
    date: 'January 2026',
    platform: 'Google',
    avatar: '/reviews/lachlan-rajasthan.jpg',
    tripPhoto: '/reviews/lachlan-rajasthan.jpg',
    photoPosition: 'center 25%',
    text: 'Rajasthan blew my mind — forts, camels, the blue city of Jodhpur. I came solo and felt completely safe the whole time. Stayed in boutique heritage properties every night. 100% booking again.',
  },
  {
    name: 'Priya Sharma',
    flag: '🇨🇦',
    country: 'Toronto, Canada',
    rating: 5,
    trip: '12-Day North India & Himalayas',
    date: 'October 2025',
    platform: 'Google',
    avatar: '/reviews/priya-himalayas.jpg',
    tripPhoto: '/reviews/priya-himalayas.jpg',
    photoPosition: 'center 28%',
    text: 'YlooTrips built me a completely custom itinerary — off-the-beaten-path temples, cooking classes in Varanasi, and the Kalka-Shimla mountain railway. Nothing was copy-pasted. Pure magic.',
  },
  {
    name: 'Chloé Dubois',
    flag: '🇫🇷',
    country: 'Paris, France',
    rating: 5,
    trip: '14-Day Kerala & South India',
    date: 'September 2025',
    platform: 'Google',
    avatar: '/reviews/chloe-kerala.jpg',
    tripPhoto: '/reviews/chloe-kerala.jpg',
    photoPosition: 'center 20%',
    text: 'Kerala — tea estates, spice gardens, traditional Kathakali arranged just for our group. The food recommendations were outstanding. YlooTrips is professional, warm, genuinely passionate. Je reviendrai!',
  },
  {
    name: 'Katrin & Markus',
    flag: '🇩🇪',
    country: 'Munich, Germany',
    rating: 4,
    trip: '10-Day Golden Triangle',
    date: 'November 2025',
    platform: 'TripAdvisor',
    avatar: '/reviews/katrin-markus-india.jpg',
    tripPhoto: '/reviews/katrin-markus-india.jpg',
    photoPosition: 'center 38%',
    text: 'Every hotel was better than expected. The private car and driver made all the difference — comfortable, safe, stopping wherever we wanted for photos. We wish we had one more day in Varanasi.',
  },
];
